//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehpardakhtMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long Id { get; set; }
        public long Amount { get; set; }
        public string PayMethod { get; set; }
        public int PayStatus { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public int BasketId { get; set; }
    }
}
